import { Customer } from '../types';

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    customerCode: 'CUST-0001',
    customerName: 'Royal Orchid Hotel',
    companyName: 'Royal Orchid Hospitality Pvt Ltd',
    contactPerson: 'Vikram Malhotra',
    mobile: '9876543210',
    email: 'contact@royalorchid.com',
    gstNumber: '29AAACR1234F1Z5',
    customerType: 'BUSINESS',
    billingAddress: { addressLine1: '12 MG Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560001', country: 'India' },
    shippingAddress: { addressLine1: '12 MG Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560001', country: 'India' },
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560001',
    creditLimit: 500000,
    openingBalance: 0,
    outstandingAmount: 127000,
    status: 'ACTIVE',
    createdAt: '2026-06-10',
    updatedAt: '2026-07-20',
    isDeleted: false,
  },
  {
    id: 'cust-2',
    customerCode: 'CUST-0002',
    customerName: 'Mehta Luxury Villa',
    companyName: 'Mehta Family Trust',
    contactPerson: 'Rajesh Mehta',
    mobile: '9820011223',
    email: 'rajesh@mehtagroup.in',
    customerType: 'INDIVIDUAL',
    billingAddress: { addressLine1: '45 Jubilee Hills', city: 'Hyderabad', state: 'Telangana', pincode: '500033', country: 'India' },
    shippingAddress: { addressLine1: '45 Jubilee Hills', city: 'Hyderabad', state: 'Telangana', pincode: '500033', country: 'India' },
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500033',
    creditLimit: 200000,
    openingBalance: 0,
    outstandingAmount: 65000,
    status: 'ACTIVE',
    createdAt: '2026-06-15',
    updatedAt: '2026-07-22',
    isDeleted: false,
  },
  {
    id: 'cust-3',
    customerCode: 'CUST-0003',
    customerName: 'Apex Corporate Office',
    companyName: 'Apex Tech Solutions Ltd',
    contactPerson: 'Sanjay Sharma',
    mobile: '9711002233',
    email: 'procurement@apextech.com',
    gstNumber: '27AAACA9876G1Z2',
    customerType: 'BUSINESS',
    billingAddress: { addressLine1: '7th Floor, BKC Tower', city: 'Mumbai', state: 'Maharashtra', pincode: '400051', country: 'India' },
    shippingAddress: { addressLine1: '7th Floor, BKC Tower', city: 'Mumbai', state: 'Maharashtra', pincode: '400051', country: 'India' },
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400051',
    creditLimit: 1000000,
    openingBalance: 0,
    outstandingAmount: 34000,
    status: 'ACTIVE',
    createdAt: '2026-06-20',
    updatedAt: '2026-07-25',
    isDeleted: false,
  },
  {
    id: 'cust-4',
    customerCode: 'CUST-0004',
    customerName: 'Skylark Decorators',
    companyName: 'Skylark Decorators LLP',
    contactPerson: 'Priya Nair',
    mobile: '9447012345',
    email: 'priya@skylark.in',
    gstNumber: '32AAACS4567H1Z8',
    customerType: 'DEALER',
    billingAddress: { addressLine1: 'MG Road Palayam', city: 'Kochi', state: 'Kerala', pincode: '682016', country: 'India' },
    shippingAddress: { addressLine1: 'MG Road Palayam', city: 'Kochi', state: 'Kerala', pincode: '682016', country: 'India' },
    city: 'Kochi',
    state: 'Kerala',
    pincode: '682016',
    creditLimit: 350000,
    openingBalance: 0,
    outstandingAmount: 118000,
    status: 'ACTIVE',
    createdAt: '2026-06-28',
    updatedAt: '2026-07-26',
    isDeleted: false,
  },
  {
    id: 'cust-5',
    customerCode: 'CUST-0005',
    customerName: 'Gupta Residency',
    companyName: '',
    contactPerson: 'Amit Gupta',
    mobile: '9810099887',
    email: 'amit.gupta@gmail.com',
    customerType: 'INDIVIDUAL',
    billingAddress: { addressLine1: 'Sector 15 Noida', city: 'Noida', state: 'Uttar Pradesh', pincode: '201301', country: 'India' },
    shippingAddress: { addressLine1: 'Sector 15 Noida', city: 'Noida', state: 'Uttar Pradesh', pincode: '201301', country: 'India' },
    city: 'Noida',
    state: 'Uttar Pradesh',
    pincode: '201301',
    creditLimit: 100000,
    openingBalance: 0,
    outstandingAmount: 0,
    status: 'INACTIVE',
    createdAt: '2026-07-01',
    updatedAt: '2026-07-27',
    isDeleted: false,
  },
];
